/*
 * 
 */

#include "/d/Gondor/defs.h"

#include TERRAIN_TYPES

#define TERRAIN_AMROTH_GARDEN \
     (TERRAIN_OUTSIDE|TERRAIN_TEMPERATE|TERRAIN_TALL_PLANT|TERRAIN_SMALL_PLANT)
#define TERRAIN_AMROTH_ROOF \
        (TERRAIN_TEMPERATE|TERRAIN_STEEP)
#define TERRAIN_AMROTH_BALCONY \
        (TERRAIN_TEMPERATE)
