#include "/d/Ansalon/balifor/flotsam/local.h"
#define SHIP_D "/d/Ansalon/balifor/flotsam/ship/"
#define CABIN       SHIP_D + "cabin"
#define CAPTAIN      SHIP_D + "captain"
#define SHIP_NAME     "The Golden Lion"
#define TICKET     SHIP_D + "ticket"
#define TICKET_NAME  "the Flotsam-Grey Havens line"
#define PRICE      28
#define ROOM    FROOM
#define S_ROOM "/d/Ansalon/balifor/flotsam/ship/room/"
#define S_NPC  "/d/Ansalon/balifor/flotsam/ship/living/"
#define S_OBJ  "/d/Ansalon/balifor/flotsam/ship/obj/"

#define DECK2     S_ROOM + "d1"
#define DECK3     S_ROOM + "d2"
#define DECK4     S_ROOM + "d3"
#define DECK5     S_ROOM + "d4"
#define DECK6     S_ROOM + "d5"
#define DECK7     S_ROOM + "d6"
#define DECK8     S_ROOM + "d7"
#define DECK9     S_ROOM + "d8"
#define DECK10     S_ROOM + "d9"
#define DECK11     S_ROOM + "u1"
#define DECK12     S_ROOM + "u2"
#define DECK13     S_ROOM + "nest"
#define CABIN1     S_ROOM + "l1"
#define CABIN2     S_ROOM + "l2"
#define CABIN3     S_ROOM + "l3"
#define CABIN4     S_ROOM + "l4"
#define CABIN5     S_ROOM + "room1"

#define OPEN_SEA   ROOM + "sea1"
#define SPARCLE_10 "/d/Genesis/start/human/town/pier10"
