#define RBIT_SELF	0x01	/* Self only.  */
#define RBIT_OTHER	0x02	/* Other only. */
#define RBIT_PRESENT	0x04
#define RBIT_VISIBLE	0x08

#define RBIT_LIVING	0x10
#define RBIT_OBJECT	0x20

#define RBIT_TEAM	0x40
#define RBIT_NOT_TEAM	0x80

#define RBIT_FRIEND	0x100
#define RBIT_ENEMY	0x200

#define RBIT_ATTACK	0x400
#define RBIT_NOT_ATTACK 0x800


#define RANGE_SELF		    (RBIT_SELF)

#define RANGE_PRESENT		    (RBIT_PRESENT)
#define RANGE_PRESENT_LIVE	    (RBIT_PRESENT | RBIT_LIVING)
#define RANGE_PRESENT_OTHER_LIVE    (RBIT_PRESENT | RBIT_OTHER)
#define RANGE_PRESENT_OBJECTS	    (RBIT_PRESENT | RBIT_OBJECT)

#define RANGE_TEAM		    (RBIT_TEAM)
#define RANGE_OTHER_TEAM	    (RBIT_TEAM | RBIT_OTHER)
#define RANGE_PRESENT_TEAM	    (RBIT_TEAM | RBIT_PRESENT)
#define RANGE_PRESENT_OTHER_TEAM    (RBIT_TEAM | RBIT_OTHER | RBIT_PRESENT)
#define RANGE_NOT_TEAM		    (RBIT_NOT_TEAM)

#define RANGE_FRIENDS		    (RBIT_LIVING | RBIT_FRIEND)
#define RANGE_ENEMIES		    (RBIT_LIVING | RBIT_ENEMY)

#define RANGE_PRESENT_ENEMIES	    (RBIT_LIVING | RBIT_ENEMY | RBIT_PRESENT)
#define RANGE_PRESENT_FRIENDS	    (RBIT_LIVING | RBIT_FRIEND | RBIT_PRESENT)

#define RANGE_PRESENT_ATTACK	    (RBIT_ATTACK | RBIT_PRESENT)
#define RANGE_PRESENT_OTHER_ATTACK  (RBIT_NOT_ATTACK | RBIT_PRESENT | RBIT_LIVING)
