/*
 *  IGARD_LIB + "furnace_funcs.c"
 *
 *  Various functions common to Isengard furnace rooms.
 *
 *  Last modified by Alto, 5 December 2001
 *
 */

#pragma strict_types

inherit "/d/Gondor/std/room.c";

#include "../igard_defs.h"

inherit IGARD_LIB + "igard_funcs.c";
inherit IGARD_LIB + "deep_funcs.c";
inherit IGARD_LIB + "quest_funcs.c";

#include <macros.h>
#include <stdproperties.h>
#include "/d/Gondor/defs.h"
#include "/d/Gondor/std/tell.c"
#include "/sys/formulas.h"

/* GLOBAL VARIABLES */

string               *handle    =({});
string               *extradesc =({});
string               Exline, Vehicle;
object               actor;


/* PROTOTYPES */

public void          furnace_add_items();
public string        furnace_extraline();
public void          furnace_quest_adds();
public void          furnace_quest_commands();
public int           pull_lever();
public int           adjust_belt();
public int           open_damper();
public int           tighten_joint();
public int           clean_corrosion();
public int           scrape_rust();
public void          move_quester_alive();
public void          move_quester_dead();
public void          shuffle_furnace();


public void
furnace_add_items()
{
    add_prop(ROOM_M_NO_TELEPORT, 1);

    add_item(({"hopper", "bin", "large bin"}), "The hopper is a large bin "
        + "into which coal is placed, after which the coal is fed onto the "
        + "conveyor belt. For the furnace to function properly, "
        + "the hopper must be filled with coal. At the moment it appears "
        + "to be full. You notice a strange green lever on the side of the "
        + "hopper.\n");
    add_item(({"coal", "coal in hopper"}), "The hopper appears to be full "
        + "of glistening black coal. It will serve as fuel to heat the water "
        + "in the pressure chamber.\n");
    add_item(({"strange green lever", "green lever", "strange lever", "lever"}),
        "On the side of the hopper is a strange green lever. The only way "
        + "to find out what it does is to pull it.\n");
    add_item(({"belt", "conveyor belt"}), "The conveyor belt moves coal from "
        + "the hopper to the combustion chamber of the furnace. It is driven "
        + "by numerous cylinders beneath the belt. At the moment the "
        + "conveyor belt appears to be running smoothly on its track.\n");
    add_item(({"cylinder", "cylinders"}), "Beneath the conveyor belt are "
        + "numerous spinning cylinders which cause it to move along its "
        + "track.\n");
    add_item(({"track"}), "The conveyor belt is kept in position by a grooved "
        + "track along which it runs.\n");
    add_item(({"chamber", "chambers"}), "Which one? There are two of them, "
        + "a combustion chamber and a pressure chamber.\n");
    add_item(({"combustion chamber"}), "The combustion chamber is where coal "
        + "is burned to heat the water in the pressure chamber. There is a "
        + "roaring fire inside. You notice a large damper extending from "
        + "the combustion chamber.\n");
    add_item(({"fire", "roaring fire"}), "Inside the combustion chamber, "
        + "a coal fire burns hot and bright, heating the water in the "
        + "pressure chamber.\n");
    add_item(({"damper", "large damper"}), "A large damper extends from the "
        + "combustion chamber. It can be twisted to increase the air entering "
        + "the chamber.\n");
    add_item(({"pressure chamber"}), "The pressure chamber is where large "
        + "quantities of water are heated to produce the steam needed for "
        + "various diabolical machines throughout Isengard. Several pipes "
        + "lead away from it and an indicator arrow provides information "
        + "about its present state.\n");
    add_item(({"water"}), "A large quantity of water fills the pressure "
        + "chamber.\n");
    add_item(({"steam"}), "Steam is generated by the pressure chamber and "
        + "is driven through the main steam pipe. Extra steam pressure is "
        + "released through the main exhaust pipe.\n");
    add_item(({"pipe", "pipes"}), "Which one? There are three of them, a "
        + "main water pipe, a main steam pipe and a main exhaust pipe.\n");
    add_item(({"arrow", "indicator", "indicator arrow", "dial"}), "The "
        + "indicator arrow points to the green part of the dial, indicating "
        + "that pressure in the chamber is normal.\n");
    add_item(({"steam pipe", "main steam pipe"}), "This is the main steam "
        + "pipe leading away from the pressure chamber. It carries "
        + "pressurized steam, which will later be used by the grinding and "
        + "squealing machines below Isengard.\n");
    add_item(({"exhaust pipe", "main exhaust pipe"}), "This is the main "
        + "leading away from the pressure chamber. It lets off extra steam "
        + "that would otherwise cause the entire system to explode.\n");
    add_item(({"water pipe", "main water pipe"}), "This is the main water "
        + "pipe leading into the pressure chamber.\n");
}


public string
furnace_extraline()
{
    int position;

    string *extradesc =
/*1*/   ({"The hopper is a large bin into which coal is placed, after which "
               + "the coal is fed onto the conveyor belt. For the "
               + "furnace to function properly, the hopper must be filled "
               + "with coal. At the moment, however, it seems to be empty. "
               + "You notice a strange green lever on the side of the "
               + "hopper.\n", 
/*2*/     "The conveyor belt moves coal from the hopper to the combustion "
               + "chamber of the furnace. It is driven by numerous "
               + "cylinders beneath the belt. At the moment, it is off "
               + "its track and does not seem to be moving.\n", 
/*3*/     "The combustion chamber is where coal is burned to heat the "
               + "water in the pressure chamber. There appears to be "
               + "no fire inside it at the moment, however. You notice "
               + "a large damper extending from the combustion chamber.\n",
/*4*/     "This is the main steam pipe leading away from the pressure "
               + "chamber. It "
               + "carries pressurized steam which will later be used by "
               + "the grinding and squealing machines below Isengard. "
               + "You notice that steam is presently escaping from a joint "
               + "halfway along the pipe.\n",
/*5*/     "This is the main exhaust pipe leading away from the pressure "
               + "chamber. "
               + "It lets off extra steam that would otherwise cause the "
               + "entire system to explode. It appears to be obstructed "
               + "with corrosion, causing a backup in the pressure chamber.\n",
/*6*/     "This is the main water pipe leading into the pressure chamber. "
               + "It appears to be obstructed with rust, causing a "
               + "pressure drop in the chamber.\n"});


    string *handle =
/*1*/     ({"lhopper", 
/*2*/       "lbelt", 
/*3*/       "lcombustion",
/*4*/       "lsteam",
/*5*/       "lexhaust",
/*6*/       "lwater"});


    Exline = ONE_OF_LIST(extradesc);

    position = member_array(Exline, extradesc);

    Vehicle = handle[position];

    return Vehicle;

}


void
furnace_quest_adds()
{
    switch (Vehicle)
    {
    case "lhopper":
        add_item(({"coal", "coal in hopper"}), "There appear to be only a few "
            + "tiny bits of coal in the hopper.\n");
        add_item(({"fire", "roaring fire"}), "The fire inside the combustion "
            + "chamber has burned so low that you can hardly even see it.\n");
        add_item(({"hopper", "bin", "large bin"}), Exline);
        add_item(({"combustion chamber"}), "The combustion chamber is where "
            + "coal is burned to heat the water in the pressure chamber. "
            + "There appears to be no fire inside it at the moment, however. "
            + "You notice a large damper extending from the combustion "
            + "chamber.\n");
        add_item(({"arrow", "indicator", "indicator arrow", "dial"}), "The "
            + "indicator arrow points to the blue part of the dial, indicating "
            + "that there is almost no pressure in the chamber.\n");
        break;

    case "lbelt":
        add_item(({"fire", "roaring fire"}), "The fire inside the combustion "
            + "chamber has burned so low that you can hardly even see it.\n");
        add_item(({"track"}), "The conveyor belt is normally kept in position "
            + "by this grooved track. The belt needs to be adjusted so that "
            + "it will run smoothly along the track once again.\n");
        add_item(({"belt", "conveyor belt"}), Exline);
        add_item(({"combustion chamber"}), "The combustion chamber is where "
            + "coal is burned to heat the water in the pressure chamber. "
            + "There appears to be no fire inside it at the moment, however. "
            + "You notice a large damper extending from the combustion "
            + "chamber.\n");
        add_item(({"arrow", "indicator", "indicator arrow", "dial"}), "The "
            + "indicator arrow points to the blue part of the dial, indicating "
            + "that there is almost no pressure in the chamber.\n");
        break;

    case "lcombustion":
        add_item(({"fire", "roaring fire"}), "The fire inside the combustion "
            + "chamber has burned so low that you can hardly even see it.\n");
        add_item(({"combustion chamber"}), Exline);
        add_item(({"arrow", "indicator", "indicator arrow", "dial"}), "The "
            + "indicator arrow points to the blue part of the dial, indicating "
            + "that there is almost no pressure in the chamber.\n");
        break;

    case "lsteam":
        add_item(({"steam pipe", "main steam pipe"}), Exline);
        add_item(({"steam"}), "Steam is whistling from a joint in the "
            + "main steam pipe.\n");
        add_item(({"joint"}), "A joint along the main steam pipe appears "
            + "to be dangerously loose, with steam whistling through it in "
            + "an ever-increasing crescendo. The joint must be tightened "
            + "to restore pressure to the chamber.\n");
        add_item(({"arrow", "indicator", "indicator arrow", "dial"}), "The "
            + "indicator arrow points to the blue part of the dial, indicating "
            + "that there is almost no pressure in the chamber.\n");
        break;

    case "lexhaust":
        add_item(({"exhaust pipe", "main exhaust pipe"}), Exline);
        add_item(({"corrosion"}), "The corrosion blocking the exhaust pipe "
           + "must be cleaned out before the furnace explodes.\n");
        add_item(({"arrow", "indicator", "indicator arrow", "dial"}), "The "
            + "indicator arrow points to the red part of the dial, indicating "
            + "that the pressure in the chamber is dangerously high.\n");
        break;

    case "lwater":
        add_item(({"water pipe", "main water pipe"}), Exline);
        add_item(({"rust"}), "The rust blocking the water pipe "
           + "must be scraped out for the chamber to regain pressure.\n");
        add_item(({"arrow", "indicator", "indicator arrow", "dial"}), "The "
            + "indicator arrow points to the blue part of the dial, indicating "
            + "that there is almost no pressure in the chamber.\n");
        break;

    default:
        write("This is one of those wrongness in space and time messages, "
            + "which means you should probably file a bugreport in this "
            + "room.\n");
        break;
    }
}


public void          
furnace_quest_commands()
{
    add_cmd_item(({"strange green lever", "green lever", "strange lever",
       "lever", "the lever"}), "pull", &pull_lever());
    add_cmd_item(({"belt", "conveyor belt", "the belt"}), "adjust", 
        &adjust_belt());
    add_cmd_item(({"damper", "large damper", "the damper"}), "twist",
        &open_damper());
    add_cmd_item(({"joint"}), "tighten", &tighten_joint());
    add_cmd_item(({"corrosion", "out corrosion", "corrosion out"}), "clean",
        &clean_corrosion());
    add_cmd_item(({"rust", "out rust", "rust out"}), "scrape", &scrape_rust());

}


public int
pull_lever()
{
    actor = TP;

    if (Vehicle != "lhopper")
    {
        set_alarm(0.0, 0.0, &write("You grab the strange green lever and "
            + "pull with all your might! A huge batch of coal falls from "
            + "a hidden chute toward the hopper.\n\n"));
        set_alarm(2.0, 0.0, &write("Unfortunately, because the hopper is "
            + "already full of coal, the coal bounces off and slams into "
            + "the pressure chamber.\n\n"));
        set_alarm(5.0, 0.0, &write("The pressure chamber explodes violently. "
            + "As your shattered body is hurled from the room, you suddenly "
            + "realize why plumbers get paid so much.\n\n"));

        tell_room(environment(actor), QCTNAME(actor) + " grabs the strange "
            + "green lever and pulls it with all " + HIS_HER(actor) + " might! "
            + "A huge batch of coal falls from a hidden chute toward the "
            + "hopper.\n", ({actor}));
        set_alarm(2.0, 0.0, &tell_room(environment(actor), "Unfortunately, "
            + "because the hopper is already full of coal, the coal bounces "
            + "off and slams into the pressure chamber.\n", ({actor})));
        set_alarm(5.0, 0.0, &tell_room(environment(actor), "The pressure "
            + "chamber explodes violently. As " + QTPNAME(actor)
            + " shattered body is hurled from the room, you suddenly realize "
            + "how fortunate you are to be standing far enough away that "
            + "you escaped " + HIS_HER(actor) + " fate.\n", ({actor})));

        shuffle_furnace();
        set_alarm(7.0, 0.0, &move_quester_dead());
        return 1;
    }

   set_alarm(0.0, 0.0, &write("You grab the strange green lever and "
            + "pull with all your might! A huge batch of coal falls from "
            + "a hidden chute into the hopper.\n\n"));
   set_alarm(0.3, 0.0, &write("Coal begins moving down the conveyor belt "
            + "toward the combustion chamber. It looks like you fixed it!\n\n"));

   tell_room(environment(actor), QCTNAME(actor) + " grabs the strange "
            + "green lever and pulls it with all " + HIS_HER(actor) + " might! "
            + "A huge batch of coal falls from a hidden chute into the "
            + "hopper. Coal quickly begins moving along the conveyor belt "
            + "toward the combustion chamber.\n", ({actor}));

    actor->add_prop(FINISHED_FURNACE_IGARD, 1);
    set_alarm(5.0, 0.0, &igard_stage_check());
    shuffle_furnace();
    move_quester_alive();
    return 1;
}


public int           
adjust_belt()
{
    actor = TP;

    if (Vehicle != "lbelt")
    {
        set_alarm(0.0, 0.0, &write("You lift the conveyor belt and give "
            + "it a strong tug.\n\n"));
        set_alarm(2.0, 0.0, &write("Unfortunately, the conveyor belt was "
            + "in its track and you have now broken it! As it squeals to "
            + "a halt, smoke begins to fill the room.\n\n"));
        set_alarm(5.0, 0.0, &write("The cylinders beneath the belt suddenly "
            + "spin loose and fly in every direction! You are smashed to "
            + "a pulp as the force blows you out of the room.\n\n"));

        tell_room(environment(actor), QCTNAME(actor) + " lifts the conveyor "
            + "belt and gives it a strong tug.\n", ({actor}));
        set_alarm(2.0, 0.0, &tell_room(environment(actor), "Unfortunately, "
            + "the conveyor belt was in its track and " + QTNAME(actor)
            + " has now broken it! As it squeals to a halt, smoke begins "
            + "to fill the room.\n", ({actor})));
        set_alarm(5.0, 0.0, &tell_room(environment(actor), "The cylinders "
            + "beneath the belt suddenly spin loose and fly in every direction! "
            + "As " + QTPNAME(actor)
            + " shattered body is hurled from the room, you suddenly realize "
            + "how fortunate you are to be standing far enough away that "
            + "you escaped " + HIS_HER(actor) + " fate.\n", ({actor})));

        shuffle_furnace();
        set_alarm(7.0, 0.0, &move_quester_dead());
        return 1;
    }

   set_alarm(0.0, 0.0, &write("You lift the conveyor belt and give it "
            + "a strong tug.\n\n"));
   set_alarm(0.3, 0.0, &write("Coal begins moving down the conveyor belt "
            + "toward the combustion chamber. It looks like you fixed it!\n\n"));

   tell_room(environment(actor), QCTNAME(actor) + " lifts the conveyor belt and "
            + "gives it a strong tug. Coal quickly begins moving along the "
            + "conveyor belt toward the combustion chamber.\n", ({actor}));

    actor->add_prop(FINISHED_FURNACE_IGARD, 1);
    set_alarm(5.0, 0.0, &igard_stage_check());
    shuffle_furnace();
    move_quester_alive();
    return 1;
}


public int           
open_damper()
{
    actor = TP;

    if (Vehicle != "lcombustion")
    {
        set_alarm(0.0, 0.0, &write("You twist the large damper, allowing "
            + "more air into the combustion chamber.\n\n"));
        set_alarm(2.0, 0.0, &write("Unfortunately, the fire in "
            + "the chamber was already burning very hot, and you have caused "
            + "it to burn even hotter! The pressure chamber begins to rattle "
            + "dangerously.\n\n"));
        set_alarm(5.0, 0.0, &write("The pressure chamber explodes violently. "
            + "As your shattered body is hurled from the room, you suddenly "
            + "realize why plumbers get paid so much.\n\n"));

        tell_room(environment(actor), QCTNAME(actor) + " twists the large "
            + "damper, allowing more air into the combustion chamber.\n",
            ({actor}));
        set_alarm(2.0, 0.0, &tell_room(environment(actor), "Unfortunately, "
            + "the fire in the chamber was already burning very hot, and "
            + QTNAME(actor) + " has caused it to burn even hotter! The pressure "
            + "chamber begins to rattle dangerously.\n", ({actor})));
        set_alarm(5.0, 0.0, &tell_room(environment(actor), "The pressure "
            + "chamber explodes violently. As " + QTPNAME(actor)
            + " shattered body is hurled from the room, you suddenly realize "
            + "how fortunate you are to be standing far enough away that "
            + "you escaped " + HIS_HER(actor) + " fate.\n", ({actor})));

        shuffle_furnace();
        set_alarm(7.0, 0.0, &move_quester_dead());
        return 1;
    }

   set_alarm(0.0, 0.0, &write("You twist the large damper, allowing more air "
       + "into the combustion chamber.\n\n"));
   set_alarm(0.3, 0.0, &write("As the water heats in the pressure chamber, "
       + "the indicator arrow returns to the green position on the dial. It "
       + "looks like you fixed it!\n\n"));

   tell_room(environment(actor), QCTNAME(actor) + " twists the large damper, "
       + "allowing more air into the combustion chamber. As the water heats "
       + "in the pressure chamber, the indicator arrow returns to the green "
       + "position on the dial.\n", ({actor}));

    actor->add_prop(FINISHED_FURNACE_IGARD, 1);
    set_alarm(5.0, 0.0, &igard_stage_check());
    shuffle_furnace();
    move_quester_alive();
    return 1;
}



public int           
tighten_joint()
{
    actor = TP;

    if (Vehicle != "lsteam")
    {
        set_alarm(0.0, 0.0, &write("You tighten the joint with all your "
            + "strength.\n\n"));
        set_alarm(2.0, 0.0, &write("Unfortunately, because it was already "
            + "tight, you manage to break the joint altogether.\n\n"));
        set_alarm(5.0, 0.0, &write("The steam pipe explodes violently. "
            + "As your shattered body is hurled from the room, you suddenly "
            + "realize why plumbers get paid so much.\n\n"));

        tell_room(environment(actor), QCTNAME(actor) + " tightens the joint "
            + "with all " + HIS_HER(actor) + " strength!\n", ({actor}));
        set_alarm(2.0, 0.0, &tell_room(environment(actor), "Unfortunately, "
            + "because it was already tight, " + QTNAME(actor) + " manages "
            + "to break the joint altogether.\n", ({actor})));
        set_alarm(5.0, 0.0, &tell_room(environment(actor), "The steam "
            + "pipe explodes violently. As " + QTPNAME(actor)
            + " shattered body is hurled from the room, you suddenly realize "
            + "how fortunate you are to be standing far enough away that "
            + "you escaped " + HIS_HER(actor) + " fate.\n", ({actor})));

        shuffle_furnace();
        set_alarm(7.0, 0.0, &move_quester_dead());
        return 1;
    }

   set_alarm(0.0, 0.0, &write("You tighten the joint with all your "
            + "strength.\n\n"));
   set_alarm(0.3, 0.0, &write("Steam stops hissing from the joint and "
            + "the indicator arrow returns to the green position on the dial. "
            + "It looks like you fixed it!\n\n"));

   tell_room(environment(actor), QCTNAME(actor) + " tightens the joint with "
            + "all " + HIS_HER(actor) + " strength. "
            + "Steam stops hissing from the joint and the indicator arrow "
            + "returns to the green position on the dial.\n", ({actor}));

    actor->add_prop(FINISHED_FURNACE_IGARD, 1);
    set_alarm(5.0, 0.0, &igard_stage_check());
    shuffle_furnace();
    move_quester_alive();
    return 1;
}


public int           
clean_corrosion()
{
    actor = TP;

    if (Vehicle != "lexhaust")
    {
        set_alarm(0.0, 0.0, &write("You stick your hand into the exhaust "
            + "pipe.\n\n"));
        set_alarm(2.0, 0.0, &write("Unfortunately, your hand obstructs the "
            + "pipe, causing the pressure chamber to rattle dangerously.\n\n"));
        set_alarm(5.0, 0.0, &write("The pressure chamber explodes violently. "
            + "As your shattered body is hurled from the room, you suddenly "
            + "realize why plumbers get paid so much.\n\n"));

        tell_room(environment(actor), QCTNAME(actor) + " sticks " + HIS_HER(actor) 
            + " hand into the exhaust pipe.\n", ({actor}));
        set_alarm(2.0, 0.0, &tell_room(environment(actor), "Unfortunately, "
            + POSSESSIVE(actor) + " hand obstructs the pipe, causing the "
            + "pressure chamber to rattle dangerously.\n", ({actor})));
        set_alarm(5.0, 0.0, &tell_room(environment(actor), "The pressure "
            + "chamber explodes violently. As " + QTPNAME(actor)
            + " shattered body is hurled from the room, you suddenly realize "
            + "how fortunate you are to be standing far enough away that "
            + "you escaped " + HIS_HER(actor) + " fate.\n", ({actor})));

        shuffle_furnace();
        set_alarm(7.0, 0.0, &move_quester_dead());
        return 1;
    }

   set_alarm(0.0, 0.0, &write("You stick your hand into the exhaust pipe.\n\n"));
   set_alarm(0.3, 0.0, &write("Yuck! You manage to pull out a huge glob of "
       + "corrosion that was obstructing the pipe. The indicator arrow returns "
       + "to the green position on the dial. It looks like you fixed it!\n\n"));

   tell_room(environment(actor), QCTNAME(actor) + " sticks " + HIS_HER(actor) 
            + " hand into the exhaust pipe. " + CAP(HE_SHE(actor))
            + " manages to "
            + "pull out a disgusting glob of corrosion that was obstructing "
            + "the pipe.\n", ({actor}));

    actor->add_prop(FINISHED_FURNACE_IGARD, 1);
    set_alarm(5.0, 0.0, &igard_stage_check());
    shuffle_furnace();
    move_quester_alive();
    return 1;
}


public int           
scrape_rust()
{
    actor = TP;

    if (Vehicle != "lwater")
    {
        set_alarm(0.0, 0.0, &write("You stick your hand into the main water "
            + "pipe.\n\n"));
        set_alarm(2.0, 0.0, &write("Unfortunately, your hand obstructs the "
            + "pipe, causing it to rattle dangerously.\n\n"));
        set_alarm(5.0, 0.0, &write("The main water pipe explodes violently. "
            + "As your shattered body is hurled from the room, you suddenly "
            + "realize why plumbers get paid so much.\n\n"));

        tell_room(environment(actor), QCTNAME(actor) + " sticks " + HIS_HER(actor) 
            + " hand into the main water pipe.\n", ({actor}));
        set_alarm(2.0, 0.0, &tell_room(environment(actor), "Unfortunately, "
            + POSSESSIVE(actor) + " hand obstructs the pipe, causing it "
            + "to rattle dangerously.\n", ({actor})));
        set_alarm(5.0, 0.0, &tell_room(environment(actor), "The main water "
            + "pipe explodes violently. As " + QTPNAME(actor)
            + " shattered body is hurled from the room, you suddenly realize "
            + "how fortunate you are to be standing far enough away that "
            + "you escaped " + HIS_HER(actor) + " fate.\n", ({actor})));

        shuffle_furnace();
        set_alarm(7.0, 0.0, &move_quester_dead());
        return 1;
    }

   set_alarm(0.0, 0.0, &write("You stick your hand into the main water "
       + "pipe.\n\n"));
   set_alarm(0.3, 0.0, &write("Yuck! You manage to scrape out a huge glob of "
       + "rust that was obstructing the pipe. The indicator arrow returns "
       + "to the green position on the dial. It looks like you fixed it!\n\n"));

   tell_room(environment(actor), QCTNAME(actor) + " sticks " + HIS_HER(actor) 
            + " hand into the main water pipe. " + CAP(HE_SHE(actor)) 
            + " manages to "
            + "scrape out a disgusting glob of rust that was obstructing "
            + "the pipe.\n", ({actor}));

    actor->add_prop(FINISHED_FURNACE_IGARD, 1);
    set_alarm(5.0, 0.0, &igard_stage_check());
    shuffle_furnace();
    move_quester_alive();
    return 1;
}


public void
move_quester_alive()
{
   return;
}


public void
move_quester_dead()
{
//    TP->add_prop(FURNACE_KILLED_ME, 1);
    TP->move_living("M", IGARD_ROOM + "catapult_room.c", 1, 0);

}


public void
shuffle_furnace()
{
    object thisplace;

    actor = TP;
    thisplace = ENV(TP);

    thisplace->furnace_add_items();
    thisplace->furnace_extraline();
    thisplace->furnace_quest_adds();

    set_alarm(8.0, 0.0, &tell_room(thisplace, "A bunch of orcs rush in to "
        + "repair the furnace. Just after they leave again, the furnace breaks "
        + "down with a clang.\n", ({actor})));

}




