/***************************************************************\

  NOTE: This file has been generated by the file
           /d/Shire/rogon/cor/corr
        Using the script file
           /d/Shire/rogon/cor/files/ex.f

  Any changes should be in the script file, not in this.

  Sir Rogon.

\***************************************************************/

#include "defs.h"

CreateMines()
{
    set_short("Mining tunnel");
    set_long(
        "You are standing in a rough winding mining tunnel" +
        ", obviously made by dwarves. " +
        "It is quite damp here, but you feel uneasy about this place, as if something above you might fall upon your head. " +
        "You notice that the tunnel slopes somewhat to the north-east. " +
        "You are also able to follow the exit winding southwest. " );
    add_exit(THIS_DIR + "mining.5","northeast");
    add_exit(THIS_DIR + "mining.3","southwest");
    add_item(({"wall","walls"}),
        "The walls are roughly cut out of the mountain.");
    add_item(({"floor"}),
        "The floor is filled with old piles of stones and pebbles.");
    add_item(({"ceiling"}),
        "The ceiling, being only inches above your head, is roughly carved.");
    add_item(({"stones","pebbles"}),
        "Stones and pebbles lie scattered around here.");
    add_item(({"ceiling"}),
        "You wonder if some room is directly above this place.");
}
