/***************************************************************\

  NOTE: This file has been generated by the file
           /d/Shire/rogon/cor/corr
        Using the script file
           /d/Shire/rogon/cor/files/ex.f

  Any changes should be in the script file, not in this.

  Sir Rogon.

\***************************************************************/

#include "defs.h"
#define IS_BLOCK "_is_shaken_up"

CreateMines()
{
    set_short("Mining tunnel");
    set_long(
        "You are standing in a rough winding mining tunnel" +
        ", probably made in search for the precious moria-silver. " +
        "You notice that the tunnel levels out in the east. " +
        "You are also able to follow the exit continuing in the west. " );
    add_exit(THIS_DIR + "mining.9","east");
    add_exit(THIS_DIR + "mining.7","west");
    add_exit(THIS_DIR + "dead_end","north", "@@check_exit@@");
    add_item(({"wall","walls"}),
        "The walls are roughly cut out of the mountain.");
    add_item(({"floor"}),
        "The floor is filled with old piles of stones and pebbles.");
    add_item(({"ceiling"}),
        "The ceiling, being only inches above your head, is roughly carved.");
    add_item(({"stones","pebbles"}),
        "Stones and pebbles lie scattered around here.");
}

int check_exit()
{
        if(!this_player()->query_prop(IS_BLOCK))
                return 0;
        write("You are still a bit shaken up to try to go back in there.\n");
        return 1;
}

/*
int check_exit()
{
        if(TP->query_wiz_level())
                return 0;
        write("Looks like there was a cave in. Knowing orcs, they might be a while in clearing it out.\n");
        return 1;
}
*/
