/***************************************************************\

  NOTE: This file has been generated by the file
           /d/Shire/rogon/cor/corr
        Using the script file
           /d/Shire/rogon/cor/files/ex.f

  Any changes should be in the script file, not in this.

  Sir Rogon.

\***************************************************************/

#include "defs.h"

CreateMines()
{
    set_short("Mining tunnel");
    set_long(
        "You are standing in a rough winding mining tunnel" +
        ". " +
        "The tunnel slopes somewhat to the north-east. " +
        "Another exit is continuing in the west. " );
    add_exit(THIS_DIR + "mining.10","northeast");
    add_exit(THIS_DIR + "mining.8","west");
    add_item(({"wall","walls"}),
        "The walls are roughly cut out of the mountain.");
    add_item(({"floor"}),
        "The floor is filled with old piles of stones and pebbles.");
    add_item(({"ceiling"}),
        "The ceiling, being only inches above your head, is roughly carved.");
    add_item(({"stones","pebbles"}),
        "Stones and pebbles lie scattered around here.");
}
