/***************************************************************\

  NOTE: This file has been generated by the file
           /d/Shire/rogon/cor/corr
        Using the script file
           /d/Shire/rogon/cor/files/ex.f

  Any changes should be in the script file, not in this.

  Sir Rogon.

\***************************************************************/

#include "defs.h"

CreateMines()
{
    set_short("Mining tunnel");
    set_long(
        "You are standing in a rough winding mining tunnel" +
        ", obviously made by dwarves. " +
        "The tunnel crawls into the north-west. " +
        "Another exit is leaving up through a hole. " );
    add_exit(THIS_DIR + "mining.15","northwest");
    add_exit(THIS_DIR + "mining.13","up");
    add_item(({"wall","walls"}),
        "The walls are roughly cut out of the mountain.");
    add_item(({"floor"}),
        "The floor is filled with old piles of stones and pebbles.");
    add_item(({"ceiling"}),
        "The ceiling, being only inches above your head, is roughly carved.");
    add_item(({"stones","pebbles"}),
        "Stones and pebbles lie scattered around here.");
}
