/*
 * height_width.c
 *
 * Lib module to be inherited into humanoid npcs.
 * It allows width and height descriptions to be
 * set directly without having to juggle height
 * and width props.
 *
 * CAVEAT: You _must_ call set_height() first, as
 *         the values generated by set_width() are
 *         dependant on those produced by set_height().
 *         You can call in either order, but calling
 *         set_height() after may screw up the values
 *         generated by set_width().
 *
 * Khail - July 16/97
 */
#pragma strict_types

#include <stdproperties.h>
#include "/d/Genesis/login/login.h"

#define TO this_object()

/*
 * Function name: get_modifier
 * Description  : Returns the appropriate modifier for
 *                height or width of an npc, based off
 *                of it's race. If the npc's race is
 *                not a standard race, 'human' race is
 *                assumed.
 * Arguments    : mode - String, either "width" or 
 *                       "height".
 * Returns      : Appropiate modifier as an integer.
 */
public int
get_modifier(string mode)
{
    int *attr;
    string race;

  /* Get the npc's race. */
    race = TO->query_race();

  /* If a non-standard race, set to human. */
    if (member_array(race, m_indexes(RACEATTR)) < 0)
        race = "human";

  /* Get the attrib array for the right race. */
    attr = RACEATTR[race];

  /* Return the appropriate attrib from the current */
  /* attrib array. */
    if (mode == "width")
        return attr[5];
    if (mode == "height")
        return attr[0];
}

/*
 * Function name: set_height
 * Description  : Allows a specific height desc to be
 *                set in an npc, and will generate the
 *                appropriate height in cm to be set
 *                as a prop to retain this desc.
 * Arguments    : str - String description of the height,
 *                      i.e. "very tall".
 * Returns      : 0 - Fail
 *                1 - Success.
 */
public int
set_height(string str)
{
    int attr,
        index,
        height;

    if ((index = member_array(str, HEIGHTDESC)) < 0)
        return 0;

    attr = get_modifier("height");

    height = (attr * SPREAD_PROC[index]) / 100 -
        random(attr / 20);
    TO->add_prop(CONT_I_HEIGHT, height);
    return 1;
}

/*
 * Function name: set_width
 * Description  : Call this function to set the width
 *                description of an npc. It will generate
 *                the necessary weight and volume props
 *                to produce the specified description,
 *                and set them in the npc accordingly.
 * Arguments    : str - String description of width,
 *                      i.e. "lean".
 * Returns      : 0 - Fail, not a valid description.
 *                1 - Success, props set.
 */
public int
set_width(string str)
{
    int attr,
        index,
        width;

  /* Fail if the specified desc is not a valid */
  /* width description as given in login.h. */
    if ((index = member_array(str, WIDTHDESC)) < 0)
        return 0;

  /* Get the appropriate racial width modifier. */
    attr = get_modifier("width");

  /* Make the actual width prop value calculation */
  /* and set the props. */
    width = (attr * TO->query_prop(CONT_I_HEIGHT) *
        (index + 7) / 10);
    width -= random(width * attr / 8000);
    TO->add_prop(CONT_I_WEIGHT, width);
    TO->add_prop(CONT_I_VOLUME, width);
    return 1;
}

public int
set_size(string height, string width)
{
    if (!set_height(height))
        return 0;

    if (!set_width(width))
        return 0;
}

public int
set_random_width()
{
    return set_width(WIDTHDESC[random(sizeof(WIDTHDESC))]);
}

public int
set_random_height()
{
    return set_height(HEIGHTDESC[random(sizeof(HEIGHTDESC))]);
}

public int
set_random_size()
{
    return set_size(HEIGHTDESC[random(sizeof(HEIGHTDESC))],
        WIDTHDESC[random(sizeof(WIDTHDESC))]);
}
