/*
 * AREA_HANDLER AUTOGENERATED ROOM
 *
 * DO NOT CHANGE ANYTHING IN THIS ROOM SINCE THE ROOM
 * AUTOREMOVES ITSELF REGULARLY.
 */

#include "../local.h"

inherit MOUNTAINS_BASE;

#include <stdproperties.h>
#include <macros.h>

string	Master_ob;	/* The master object */
int	Timeout;	/* Timeout time */
string *herbs = 0;

public nomask void set_cleanup_time(int time);



void
create_mountains_room()
{
    setuid();
    seteuid(getuid());

