inherit "/d/Shire/std/clone_handler";

#include "/d/Gondor/defs.h"
#include "defs.h"

void
create_clone_handler()
{
    set_default_area(CAMP_ROOM_DIR);

    add_clone(CAMP_NPC_DIR + "guard", 1, 20,
        ({CAMP_ROOM_DIR + "f1.c", CAMP_ROOM_DIR + "f10.c",
        CAMP_ROOM_DIR + "f11.c", CAMP_ROOM_DIR + "f12.c",
        CAMP_ROOM_DIR + "f13.c", CAMP_ROOM_DIR + "f14.c",
        CAMP_ROOM_DIR + "f15.c", CAMP_ROOM_DIR + "f16.c",
        CAMP_ROOM_DIR + "f17.c", CAMP_ROOM_DIR + "f18.c",
        CAMP_ROOM_DIR + "f19.c", CAMP_ROOM_DIR + "f2.c",
        CAMP_ROOM_DIR + "f20.c", CAMP_ROOM_DIR + "f21.c",
        CAMP_ROOM_DIR + "f22.c", CAMP_ROOM_DIR + "f23.c",
        CAMP_ROOM_DIR + "f24.c", CAMP_ROOM_DIR + "f25.c",
        CAMP_ROOM_DIR + "f26.c", CAMP_ROOM_DIR + "f27.c",
        CAMP_ROOM_DIR + "f28.c", CAMP_ROOM_DIR + "f29.c",
        CAMP_ROOM_DIR + "f3.c",  CAMP_ROOM_DIR + "f30.c",
        CAMP_ROOM_DIR + "f31.c", CAMP_ROOM_DIR + "f4.c",
        CAMP_ROOM_DIR + "f5.c",  CAMP_ROOM_DIR + "f6.c",
        CAMP_ROOM_DIR + "f7.c",  CAMP_ROOM_DIR + "f8.c",
        CAMP_ROOM_DIR + "f9.c",  CAMP_ROOM_DIR + "m1.c",
        CAMP_ROOM_DIR + "m10.c", CAMP_ROOM_DIR + "m10t.c",
        CAMP_ROOM_DIR + "m11.c", CAMP_ROOM_DIR + "m12.c",
        CAMP_ROOM_DIR + "m13.c", CAMP_ROOM_DIR + "m14.c",
        CAMP_ROOM_DIR + "m15.c", CAMP_ROOM_DIR + "m16.c",
        CAMP_ROOM_DIR + "m17.c", CAMP_ROOM_DIR + "m18.c",
        CAMP_ROOM_DIR + "m19.c", CAMP_ROOM_DIR + "m2.c",
        CAMP_ROOM_DIR + "m20.c", CAMP_ROOM_DIR + "m21.c",
        CAMP_ROOM_DIR + "m22.c", CAMP_ROOM_DIR + "m23.c",
        CAMP_ROOM_DIR + "m24.c", CAMP_ROOM_DIR + "m25.c",
        CAMP_ROOM_DIR + "m26.c", CAMP_ROOM_DIR + "m3.c",
        CAMP_ROOM_DIR + "m4.c",  CAMP_ROOM_DIR + "m5.c",
        CAMP_ROOM_DIR + "m6.c",  CAMP_ROOM_DIR + "m7.c",
        CAMP_ROOM_DIR + "m8.c",  CAMP_ROOM_DIR + "m9.c",
        CAMP_ROOM_DIR + "p1.c",  CAMP_ROOM_DIR + "p2.c",
        CAMP_ROOM_DIR + "p3.c"}));
    add_clone(CAMP_NPC_DIR + "scout", 2, 20,
        ({CAMP_ROOM_DIR + "f1.c", CAMP_ROOM_DIR + "f10.c",
        CAMP_ROOM_DIR + "f11.c", CAMP_ROOM_DIR + "f12.c",
        CAMP_ROOM_DIR + "f13.c", CAMP_ROOM_DIR + "f14.c",
        CAMP_ROOM_DIR + "f15.c", CAMP_ROOM_DIR + "f16.c",
        CAMP_ROOM_DIR + "f17.c", CAMP_ROOM_DIR + "f18.c",
        CAMP_ROOM_DIR + "f19.c", CAMP_ROOM_DIR + "f2.c",
        CAMP_ROOM_DIR + "f20.c", CAMP_ROOM_DIR + "f21.c",
        CAMP_ROOM_DIR + "f22.c", CAMP_ROOM_DIR + "f23.c",
        CAMP_ROOM_DIR + "f24.c", CAMP_ROOM_DIR + "f25.c",
        CAMP_ROOM_DIR + "f26.c", CAMP_ROOM_DIR + "f27.c",
        CAMP_ROOM_DIR + "f28.c", CAMP_ROOM_DIR + "f29.c",
        CAMP_ROOM_DIR + "f3.c",  CAMP_ROOM_DIR + "f30.c",
        CAMP_ROOM_DIR + "f31.c", CAMP_ROOM_DIR + "f4.c",
        CAMP_ROOM_DIR + "f5.c",  CAMP_ROOM_DIR + "f6.c",
        CAMP_ROOM_DIR + "f7.c",  CAMP_ROOM_DIR + "f8.c",
        CAMP_ROOM_DIR + "f9.c",  CAMP_ROOM_DIR + "m1.c",
        CAMP_ROOM_DIR + "m10.c", CAMP_ROOM_DIR + "m10t.c",
        CAMP_ROOM_DIR + "m11.c", CAMP_ROOM_DIR + "m12.c",
        CAMP_ROOM_DIR + "m13.c", CAMP_ROOM_DIR + "m14.c",
        CAMP_ROOM_DIR + "m15.c", CAMP_ROOM_DIR + "m16.c",
        CAMP_ROOM_DIR + "m17.c", CAMP_ROOM_DIR + "m18.c",
        CAMP_ROOM_DIR + "m19.c", CAMP_ROOM_DIR + "m2.c",
        CAMP_ROOM_DIR + "m20.c", CAMP_ROOM_DIR + "m21.c",
        CAMP_ROOM_DIR + "m22.c", CAMP_ROOM_DIR + "m23.c",
        CAMP_ROOM_DIR + "m24.c", CAMP_ROOM_DIR + "m25.c",
        CAMP_ROOM_DIR + "m26.c", CAMP_ROOM_DIR + "m3.c",
        CAMP_ROOM_DIR + "m4.c",  CAMP_ROOM_DIR + "m5.c",
        CAMP_ROOM_DIR + "m6.c",  CAMP_ROOM_DIR + "m7.c",
        CAMP_ROOM_DIR + "m8.c",  CAMP_ROOM_DIR + "m9.c",
        CAMP_ROOM_DIR + "p1.c",  CAMP_ROOM_DIR + "p2.c",
        CAMP_ROOM_DIR + "p3.c"}));

    add_clone(CAMP_NPC_DIR + "captain", 3, 10,
        ({CAMP_ROOM_DIR + "f1.c", CAMP_ROOM_DIR + "f10.c",
        CAMP_ROOM_DIR + "f11.c", CAMP_ROOM_DIR + "f12.c",
        CAMP_ROOM_DIR + "f13.c", CAMP_ROOM_DIR + "f14.c",
        CAMP_ROOM_DIR + "f15.c", CAMP_ROOM_DIR + "f16.c",
        CAMP_ROOM_DIR + "f17.c", CAMP_ROOM_DIR + "f18.c",
        CAMP_ROOM_DIR + "f19.c", CAMP_ROOM_DIR + "f2.c",
        CAMP_ROOM_DIR + "f20.c", CAMP_ROOM_DIR + "f21.c",
        CAMP_ROOM_DIR + "f22.c", CAMP_ROOM_DIR + "f23.c",
        CAMP_ROOM_DIR + "f24.c", CAMP_ROOM_DIR + "f25.c",
        CAMP_ROOM_DIR + "f26.c", CAMP_ROOM_DIR + "f27.c",
        CAMP_ROOM_DIR + "f28.c", CAMP_ROOM_DIR + "f29.c",
        CAMP_ROOM_DIR + "f3.c",  CAMP_ROOM_DIR + "f30.c",
        CAMP_ROOM_DIR + "f31.c", CAMP_ROOM_DIR + "f4.c",
        CAMP_ROOM_DIR + "f5.c",  CAMP_ROOM_DIR + "f6.c",
        CAMP_ROOM_DIR + "f7.c",  CAMP_ROOM_DIR + "f8.c",
        CAMP_ROOM_DIR + "f9.c",  CAMP_ROOM_DIR + "m1.c",
        CAMP_ROOM_DIR + "m10.c", CAMP_ROOM_DIR + "m10t.c",
        CAMP_ROOM_DIR + "m11.c", CAMP_ROOM_DIR + "m12.c",
        CAMP_ROOM_DIR + "m13.c", CAMP_ROOM_DIR + "m14.c",
        CAMP_ROOM_DIR + "m15.c", CAMP_ROOM_DIR + "m16.c",
        CAMP_ROOM_DIR + "m17.c", CAMP_ROOM_DIR + "m18.c",
        CAMP_ROOM_DIR + "m19.c", CAMP_ROOM_DIR + "m2.c",
        CAMP_ROOM_DIR + "m20.c", CAMP_ROOM_DIR + "m21.c",
        CAMP_ROOM_DIR + "m22.c", CAMP_ROOM_DIR + "m23.c",
        CAMP_ROOM_DIR + "m24.c", CAMP_ROOM_DIR + "m25.c",
        CAMP_ROOM_DIR + "m26.c", CAMP_ROOM_DIR + "m3.c",
        CAMP_ROOM_DIR + "m4.c",  CAMP_ROOM_DIR + "m5.c",
        CAMP_ROOM_DIR + "m6.c",  CAMP_ROOM_DIR + "m7.c",
        CAMP_ROOM_DIR + "m8.c",  CAMP_ROOM_DIR + "m9.c",
        CAMP_ROOM_DIR + "p1.c",  CAMP_ROOM_DIR + "p2.c",
        CAMP_ROOM_DIR + "p3.c"}));

    set_clone_handler_id("Dunlending Camp Clone Handler");
}
