/*Created by Stevenson*/
#include "/d/Krynn/common/defs.h"
#include "/d/Krynn/icewall/local.h"
#include <macros.h>
#include <stdproperties.h>
inherit ICEINROOM;

create_icewall_room()
{
   set_short("Falling Water");
   set_long(
      "This is a very dark room. Frozen mists cover the watery "
      + "surface of the lake like a blanket. Along the south wall "
      + "you see water pouring out through a large hole. "
      +"\n");
   
   add_prop(ROOM_I_TYPE,ROOM_IN_WATER);
   add_item("mist","The mists are generated by the heat of your "
      + "passing through the arctic waters.\n");
   add_item("lake","The lake is north and east of you.\n");
   add_item("wall","The south cavern wall contains a large hole "
      + "in it about nine feet above the lake.\n");
   add_item("hole","Water pours out of the hole into the lake at your "
      + "feet.\n");
   add_item("water","The water falls down from the hole and lands at "
      + "your feet.\n");
   
   add_exit(CAVE + "cavern1.c", "northeast");
}
