#define STAND_PARENT  "/d/Shire/common/"
#define STAND_DIR     STAND_PARENT + "herbs/"
#define STAND_HERB    STAND_PARENT + "herbs/"
#define STAND_MONSTER STAND_PARENT + "monster/"
#define STAND_OBJ     STAND_PARENT + "obj/"
