/*
 * AREA_HANDLER AUTOGENERATED ROOM
 *
 * DO NOT CHANGE ANYTHING IN THIS ROOM SINCE THE ROOM
 * AUTOREMOVES ITSELF REGULARLY.
 */

#include "/d/Krynn/common/defs.h"

inherit R_FILE

#include <stdproperties.h>
#include <macros.h>

string	Master_ob;	/* The master object */
int	Timeout;	/* Timeout time */
int     gAlarm_clean;   /* The alarm id */

public nomask void set_cleanup_time(int time);

void
create_room()
{
    setuid();
    seteuid(getuid());
