/*
 * AREA_HANDLER AUTOGENERATED ROOM
 *
 * DO NOT CHANGE ANYTHING IN THIS ROOM SINCE THE ROOM
 * AUTOREMOVES ITSELF REGULARLY.
 */

#include "../local.h"

inherit ROOM_BASE
inherit HERBSEARCHNEW
inherit CONQUER_BASE

#include <stdproperties.h>
#include <macros.h>

string	Master_ob;	/* The master object */
int	Timeout;	/* Timeout time */
string *herbs = 0;

public nomask void set_cleanup_time(int time);

void
reset_road_room()
{
    set_searched(random(3));
    reset_conquer_room();
}

void
init()
{
    init_conquer();
    ::init();
}

void
create_road_room()
{
    setuid();
    seteuid(getuid());
    
    set_area_name(AREA_NAME);

