
#define ALEIPSO "/d/Calia/worshippers/spells/aleipso.h"
#define ANEMOS "/d/Calia/worshippers/spells/anemos.h"
#define TEIKOS "/d/Calia/worshippers/spells/teikos.h"
#define TEIKOS_ARM "teikos_armour"
#define TEIKOS_OBJ "/d/Calia/worshippers/spells/tei_arm"
#define PURKAGIA "/d/Calia/worshippers/spells/purkagia.h"
#define PSOTIA "/d/Calia/worshippers/spells/psotia.h"
#define DJINNI "/d/Calia/worshippers/spells/fire.c"
#define KATARAKTAS "/d/Calia/worshippers/spells/kataraktas.h"
#define WEIRD "/d/Calia/worshippers/spells/water.c"
#define CHOMA "/d/Calia/worshippers/spells/choma.h"
#define GOLEM "/d/Calia/worshippers/spells/earth.c"
#define STOUS "/d/Calia/worshippers/spells/stous.h"
#define SPIRIT "/d/Calia/worshippers/spells/air.c"
#define WOR_CREATURE_SUMMONED "_worshipper_creature_summoned"
#define AELIKIAS "/d/Calia/worshippers/spells/aelikias.h"
#define THANATOS "/d/Calia/worshippers/spells/thanatos.h"
