/*
 * Standard Spell Resistance Object
 *
 * This is the spell object for the standard Genesis Magic System Resistance
 * spell. 
 *
 * Created by Petros, March 2010
 */

#pragma strict_types
#pragma save_binary

#include <stdproperties.h>
#include <ss_types.h>
#include <macros.h>
#include <wa_types.h>
#include <files.h>
#include "/d/Krynn/common/defs.h"

#include "../defs.h"

#include "/d/Genesis/specials/local.h"
inherit SPELL_OBJ_DIR + "spell_obj_base";

public mapping      resistance_mapping = ([ ]);

/*
 * Function:    create_spell_object
 * Description: Override this to customize properties for the spell object
 */
public void 
create_spell_object()
{
    set_name("_protect_dragon_fear_object_");
    set_short("ward against dragon fear object");    
    set_long("This is the standard resistance spell's object. It protects "
        + "one against certain elements.\n");

    add_prop(OBJ_S_WIZINFO, "This is a spell object " +
                            "created by the protect dragon fear spell.\n");
    set_spell_effect_desc("fear resistance");    
}

public string
query_subloc_name(string element) 
{
    return "_subloc_resistance" + element;
}


/*
 * Function:    setup_spell_effect
 * Description: This is called to set up all the things for the
 *              spell. Must call the parent's setup_spell_effect
 *              in order to get the maintainence stuff.
 */
public int
setup_spell_effect()
{
    int result = ::setup_spell_effect();
    if (!result)
    {
        return result;
    }

    int power = query_spell_effect_power();
    // Power determines how long the spell lasts
    // int duration = power * 5; // F_PENMOD(60, 100) = 396 * 5 = 33 minutes

    set_dispel_time(get_default_spell_time());
    
    // The input to the spell object will be a mapping of element type and
    // the combat aid that the element type should have.
    mapping resistance_aid = query_spell_effect_input();
    object target = query_effect_target();
    foreach (string element, int aid : resistance_aid)
    {
        // Combat aid => Effect percentage calculation is done using the
        // following formula.
        //   e = (100 * c) / (100 + c)
        resistance_mapping[element] = (100 * aid) / (100 + aid);
        target->add_subloc(query_subloc_name(element), this_object());        
    }
    
    return result;
}

/* 
 * Function:    query_magic_protection
 * Description: This will return the resistence percentages stored
 *              for this resistance object.
 */
public mixed
query_magic_protection(string prop, object what)
{
    if (resistance_mapping[prop])
    {
        return ({ resistance_mapping[prop], 1 });
    }

    return ::query_magic_protection(prop, what);
}

/*
 * Function:    hook_spell_effect_started
 * Description: Override this to customize the message when this spell effect
 *              is added to th target.
 */
public void
hook_spell_effect_started()
{
    object target = query_effect_target();

    if (objectp(target))
    {
        target->catch_tell("You feel yourself protected from the magical " +
           "fear generated by dragons.\n");
        tell_room(environment(target), QCTNAME(target) + " is warded from "
            + "the magical fear of dragons.\n", ({ target }));
    }

    target->add_prop(LIVE_I_NO_DRAGONFEAR, 
                     target->query_prop(LIVE_I_NO_DRAGONFEAR) + 1);
    
}

/*
 * Function:    hook_spell_effect_ended
 * Description: Override this to customize the message when this spell effect
 *              is dispelled.
 */
public void
hook_spell_effect_ended()
{
    object target = query_effect_target();

    target->add_prop(LIVE_I_NO_DRAGONFEAR, 
                     target->query_prop(LIVE_I_NO_DRAGONFEAR) - 1);

    if(target->query_ghost())
        return;

    if (objectp(target))
    {
        target->catch_tell("You feel your ward against dragon fear disappear.\n");
        tell_room(environment(target), QCTNAME(target) + " is no longer " +
           "warded from the magical fear of dragons.\n", ({ target }));
    }

}

/*
 * Function:    hook_spell_effect_warn_fading
 * Description: Override this to customize the message for when
 *              the effect has only a minute left.
 */
public void
hook_spell_effect_warn_fading()
{
    object target = query_effect_target();
    
    if (objectp(target))
    {
        target->catch_tell("You feel the ward against dragon fear begin to "
            + "fade.\n");
    }
}

/* 
 * Function:    hook_spell_effect_not_maintained
 * Description: Override this to describe the effect when the caster
 *              cannot maintain the effect.
 */
public void
hook_spell_effect_not_maintained()
{
    object caster = query_effect_caster();
    
    if (objectp(caster))
    {
        caster->catch_tell("You are mentally unable to maintain "
            + "the ward against dragon fear.\n");
    }    
}

/*
 * Function name: leave_env
 * Description:   Called when this object is moved from another object
 * Arguments:     from - The object this object is moved from
 *		  to   - The object to which this object is being moved
 */
void
leave_env(object from, object to)
{
    ::leave_env(from, to);

    if (interactive(from))
    {
        foreach (string element, int amount : resistance_mapping)
        {
            object subloc_obj = from->query_subloc_obj(query_subloc_name(element));
            if (subloc_obj == this_object())
            {
                RESISTANCE_OBJECT->move_subloc_owner(from, subloc_obj);            
            }
        }
    }
}

/*
 * Function:    query_subloc_description
 * Description: When someone examines a person with this spell effect,
 *              they will see whatever is returned by this function.
 */
public string
query_subloc_description(object on, object for_obj, string element)
{
    string subloc = RESISTANCE_OBJECT->query_resistance_description(element);
    if (for_obj == on) {
        subloc = "Your " + subloc;
    } else {
        subloc = capitalize(on->query_possessive()) + " " + subloc;
    }
    return subloc;
}

public string
show_subloc(string subloc, object on, object for_obj)
{
    string data;

    if (on->query_prop(TEMP_SUBLOC_SHOW_ONLY_THINGS))
        return "";

    string element;
    if (!sscanf(subloc, "_subloc_resistance%s", element))
    {
        return "";
    }

    // Don't want a subloc description... otherwise alter this    
    return "";
}

