// CREATURE:  noseeum.c

    /* Calia Domain

    HISTORY

    [98-04-30] Created by Uhclem from
    [C:\CALIA\CENTRAL\FOREST\SPECIALS\NOSEEUM.DOC].

    PURPOSE

    This is not a typical monster! This is an invisible creature that is cloned
    into a forest room to transmit text between players hiding in trees and
    players on the ground below. The messages are based on the catch_msg texts
    generated by these players. The intent is to simulate what can be seen and
    heard by people in close proximity but separated by dense foliage. */

// INCLUSIONS AND DEFINITIONS

inherit "/std/monster";

#include <wa_types.h>
#include <ss_types.h>
#include <macros.h>
#include <filter_funs.h>
#include <stdproperties.h>
#include <formulas.h>
#include "defs.h"

// GLOBAL VARIABLES

object *Channels = ({});  /* List of rooms or objects receiving messages. */

// FUNCTIONS

// Function:  open_channel(object)

/*

Purpose:  open a line of communication between the noseeum and the environment
it sends messages to. In general, noseeums work in pairs, relaying messages
between adjacent rooms or a room and a container, although one noseeum in a
room can communicate with several containers in that room.

Arguments:  object, a reference to a container or a room.

Returns:  nothing.

*/

void
open_channel(object ob)

    {

    if (member_array(ob, Channels)== -1) Channels += ({ob});

    }

// Function:  close_channel(object)

/*

Purpose:  close a line of communication between a noseeum inside the tree and
one outside; this is done when a tree is evacuated.

Arguments:  object (optional) to be removed from the Channels list. If called
without arguments, this function removes the noseeum from the game.

Returns:  nothing.

*/

varargs void
close_channel(object ob)

    {

    if (ob)

        {

        if (member_array(ob, Channels) != -1) Channels -= ({ob});

        }

    if (!sizeof(Channels) || !Channels[0]) remove_object();

    }

// Function:  catch_msg(str, from_player)

/*

Purpose:  shuttle messages between players inside the tree and those outside.

Arguments:  none.

Returns:  nothing.

*/

void
catch_msg(mixed str, object from_player)

    {

    object another_noseeum;
    int m = sizeof(Channels);
    int n;

    for (n=0; n<m; n+=1)

        {

        another_noseeum = present("no-see-um", Channels[n]);
        tell_room(Channels[n], str, ({another_noseeum}), from_player);

        }

    }

// CREATURE DEFINITION

    create_monster()

        {

        set_name("no-see-um");
        set_short("calian forest no-see-um");
        set_long("This creature is invisible.\n");
        set_tell_active(1);

        /*  PROPERTIES  */

        add_prop(CONT_I_VOLUME, 1);
        add_prop(CONT_I_WEIGHT, 1);
        add_prop(CONT_I_MAX_VOLUME, 1);
        add_prop(CONT_I_MAX_WEIGHT, 1);
        add_prop(OBJ_I_INVIS, 100);

        add_prop(OBJ_S_WIZINFO,
            "This creature performs important tasks in" +
            " the forests of Calia. It does not interact with" +
            " mortals and should never be detected by them.\n");

        }
