#include "../defs.h"
#define AKOUTARI_OB "/d/Calia/walkers/fire/spells/akoutari_obj"
#define ASPIDA_ARM "/d/Calia/walkers/fire/spells/aspida_arm"
#define ASPIDA_OBJ "_aspida_arm_"
#define BROMOS_OB "/d/Calia/walkers/fire/spells/bromos_obj"
#define TUPHLONO_OB "/d/Calia/walkers/fire/spells/tuphlono_obj"
#define AEMERA_OB "/d/Calia/walkers/fire/spells/aemera_ob"
#define AEMERA_OBJ "_aemera_obj_"
#define AEMERA_SHADOW "/d/Calia/walkers/fire/spells/aemera_shadow"
#define PHLOGAPHULO_WEP "/d/Calia/walkers/fire/spells/phlogaphulo_wep"
#define PHOTITSO_OBJ "/d/Calia/walkers/fire/spells/photitso_ob"
#define PHOTITSO_OB "/d/Calia/walkers/fire/spells/photitso_ob"
#define LAMPAS_OBJ "/d/Calia/walkers/fire/spells/lampas_obj"
#define EKTOMON_OBJ "/d/Calia/walkers/fire/spells/ektomon_obj"
#define AITHOS_OBJ "/d/Calia/walkers/fire/spells/aithos_obj"