   set_act_time(10);
   add_act("emote stares at you suspiciously.");
   add_act("emote shouts orders to his men in a foreign tounge.");
   add_act("shout Be vigilant men! There are intruders in the area.");
   add_act("say Where are the reports from my Trieterions?!");
   add_act("say The infidels crushed and driven out.");
   add_act("emote paces impatiently.");
   add_act("say The followers of false gods shall not spread their foul teachings here.");
   add_act("say The streets of Argos shall flow with the blood of loyalists.");
   set_cact_time(5);
   add_cact("emote swings his weapon over his head triumphantly.");
   add_cact("shout You shall die for your intrusion, infidel!");
   add_cact("shout I shall crush your head like a melon, infidel!");
   add_cact("emote cackles maniacally with an evil glare.");
   add_cact("say Your corpse on a pole shall be a warning to others, intruder!");
   add_cact("say Your kind will be crushed by the heel of Kretos, infidel!");
   add_cact("emote yells a shrill battle cry!");
