#include "defs.h"

#define S_LOCAL_ARM_DIR		(S_AREA_ARM_DIR + S_AREA_FORT)
#define S_LOCAL_NPC_DIR		(S_AREA_NPC_DIR + S_AREA_FORT)
#define S_LOCAL_OBJ_DIR		(S_AREA_OBJ_DIR + S_AREA_FORT)
#define S_LOCAL_WEP_DIR		(S_AREA_WEP_DIR + S_AREA_FORT)
#define S_LOCAL_ROOM_DIR	(S_AREA_ROOM_DIR + S_AREA_FORT)
