string *map()
{ return ({
" Mrr          RpTppppppppppK  ",
" Mpprrrrr    RpppHppppppKKK   ",
"  Mprrpprrr RpppppTpppppK     ",
"  MpppTpppRRRRppppppppppK     ",
"   MpppHppppTRppppppppppK     ",
"    MEppTpppRRRpppBpppppK     ",
"    MpppppppRppTppppTpppK     ",
"  MMppTpppppRRppppppppppK     ",
" MTppppppTpppRRppTpppppppK    ",
" MPPPPPPPPPPPPPPPPPPPPPPKK    ",
" MTppppTppppRRRpTpppppppppK   ",
"  MpppppppppRppppppTppTpppK   ",
"   MppppTpppRpppppppppppppK   ",
"   MpTppppppRRRpHTppppppppK   ",
"    MppppppppRRppppppppppppK  ",
"   MMppppppppRpTppppppppppK   ",
"  MpppppTppppRpppppppTppppK   ",
" MppTpHppppppRRppppppppppTK   ",
" MppppppppTppRppTpppppppppK   ",
"  MMpppppppppRppppTppppppppK  ",
"  MMpTpppppppRRRpppHppTppppK  ",
" MppppppTppTppRRppppTppppppK  ",
" MpTpppppHppppRppppppppppTpK  ",
" MpppppppppppRRppTpppppppppK  ",
"  MpppTpppppRRpTpppppppppppK  ",
" MMpppppppppRpppppTppTHppppK  ",
"MpppppppTpppRTppppppppppppTK  ",
"MpppppppppppRRppppppppppppppK ",
" MpppTpppppppRpTpppTppppppppK ",
" MpppppppppppRRpppppppppppppK ",
"  MrrpppppTppRRpHTppppTpTpppK ",
"     rrrpppppRpppppppppHpppppK",
"        rpppRRppppppTppppppppK",
"         rrpRppppppppppTppppK ",
"           RRpppppTpppppppppK ",
"             RRTppppHppppppK  ",
"              RppppppTpppppK  ",
"             RpppTppppppppK   ",
"             RTppppTppppTpK   " });
}
