#include "/d/Calia/argos/argos.h"
#define OBJ_DIR    ARGOS_DIR+"nwterr/objects/" 
#define NPC_DIR    ARGOS_DIR+"nwterr/monsters/"
#define WEAPON_DIR    ARGOS_DIR+"nwterr/weapons/"
#define ARMOUR_DIR    ARGOS_DIR+"nwterr/armours/"
#define ROOM_DIR   ARGOS_DIR+"nwterr/rooms/"
#define SWTERR_ROOM_DIR  ARGOS_DIR+"swterr/rooms/"
#define KR_HERBSEARCH "/d/Krynn/common/herbsearch.h"
#define KRHERBS "/d/Kalad/common/herbs/"
#define KHERBS "/d/Krynn/common/herbs/"
#include "/d/Calia/abbrev.h"
