#include "/d/Calia/zima/argos/argos.h"
#include "/d/Calia/zima/argos/specials/teamsupt.c"
#define OBJ_DIR          SWTERR_DIR+"objects/"
#define NPC_DIR          SWTERR_DIR+"monsters/"
#define WEAPON_DIR       SWTERR_DIR+"weapons/"
#define ARMOUR_DIR       SWTERR_DIR+"armours/"
#define ROOM_DIR         SWTERR_DIR+"rooms/"
