   set_act_time(10);
   add_act("emote looks at you suspiciously.");
   add_act("emote scans the area vigilantly.");
   add_act("emote inspects his equipment carefully.");
   add_act("emote gives his weapon and admiring look.");
   add_act("say Our ranks are growing daily. Soon an easy victory will be ours.");
   add_act("say I'll be made a noble by the time this is over.");
   add_act("say We'll drive the infidels from our valley, and peace will return.");
   add_act("emote paces around confidently.");
   add_act("emote stands at attention proudly.");
   set_cact_time(5);
   add_cact("emote swings his weapon over his head triumphantly.");
   add_cact("shout You shall die for your intrusion, infidel!");
   add_cact("shout Death to all foreigners!");
   add_cact("emote cackles maniacally with an evil glare.");
   add_cact("say Your corpse on a pole shall be a warning to others, intruder!");
   add_cact("say Your kind will be crushed by the heel of Kretos, infidel!");
   add_cact("emote yells a shrill battle cry!");
   add_cact("say Reinforcements are on their way! Run while you can, intruder!");
