/***************************************************************\

  NOTE: This file has been generated by the file
           /d/Shire/rogon/cor/corr
        Using the script file
           /d/Shire/rogon/cor/files/ex.f

  Any changes should be in the script file, not in this.

  Sir Rogon.

\***************************************************************/

#include "defs.h"

CONSTRUCT_ROOM
{
    set_short("Mining tunnel");
    set_long(
        "You are standing in a rough winding mining tunnel" +
        ", probably made in search for the precious moria-silver. " +
        "The tunnel levels out in the west. " +
        "Another exit is leaving somewhat south-east. " );
    add_exit("/d/Shire/common/mines/mining.16","west");
    add_exit("/d/Shire/common/mines/mining.14","southeast");
    add_item(({"wall","walls"}),
        "The walls are roughly cut out of the mountain.");
    add_item(({"floor"}),
        "The floor is filled with old piles of stones and pebbles.");
    add_item(({"ceiling"}),
        "The ceiling, being only inches above your head, is roughly carved.");
    add_item(({"stones","pebbles"}),
        "Stones and pebbles lie scattered around here.");
}
