/* /d/Earthsea/sys/macros.h - A few useful macros
 *
 * DO NOT EDIT THIS FILE unless you have explicitly been given
 * permission to do so.  If you have been given permission, and
 * you edit this file, BE SURE THAT THERE ARE NO ERRORS in it.
 */
 
#ifndef EARTHSEA_DEFS
#define EARTHSEA_DEFS

#include <std.h>

#define ROKE_OPEN
#define ROKE_DOMAIN_NAME "Roke"

#define EARTHSEA_DOMAIN_NAME "Earthsea"

#define TP this_player()
#define TO this_object()

/*
 * IS_WIZ(x) - determine if an object is a wizard.  This only needs to
 *             be used if security is very important; otherwise, simply
 *             use x->query_wiz_level()
 */
#define IS_WIZ(x) (interactive(x) && \
   SECURITY->query_wiz_rank(x->query_real_name()))

/*
 * EARTSEA_WIZ(x) - determine if an object is a wizard in the Earthsea domain
 */
#ifdef ROKE_OPEN
#define EARTHSEA_WIZ(x) (interactive(x) && \
   (SECURITY->query_wiz_dom(x->query_real_name()) == EARTHSEA_DOMAIN_NAME) || \
   (SECURITY->query_wiz_dom(x->query_real_name()) == ROKE_DOMAIN_NAME))
#else
#define EARTHSEA_WIZ(x) (interactive(x) && \
   (SECURITY->query_wiz_dom(x->query_real_name()) == EARTHSEA_DOMAIN_NAME)
#endif

/*
 * Set the euid of this object to the file's owner
 */
#define FIXEUID         { setuid(); seteuid(getuid()); }


#endif
