/* /d/Earthsea/sys/paths.h - #defines for domain pathsnames
 *
 * DO NOT EDIT THIS FILE unless you have explicitly been given
 * permission to do so.  If you have been given permission, and
 * you edit this file, BE SURE THAT THERE ARE NO ERRORS in it.
 *
 * This file is ONLY FOR PATHNAMES.
 *
 * Only place pathnames in this file if they are used in several
 * areas in the domain; otherwise, place them in a header file
 * for the area itself.
 */

#ifndef EARTHSEA_PATHS
#define EARTHSEA_PATHS

#define EARTHSEA_DIR  "/d/Earthsea/"

#define EARTHSEA_STD_DIR     EARTHSEA_DIR + "std/"
#define EARTHSEA_LIB_DIR     EARTHSEA_DIR + "lib/"
#define EARTHSEA_OBJ_DIR     EARTHSEA_DIR + "obj/"
#define EARTHSEA_SYS_DIR     EARTHSEA_DIR + "sys/"
#define EARTHSEA_HERBS_DIR   EARTHSEA_DIR + "herbs/"
#define EARTHSEA_LOG_DIR     EARTHSEA_DIR + "log/"

#define EARTHSEA_ROOM        EARTHSEA_STD_DIR + "room"
#define EARTHSEA_MONSTER     EARTHSEA_STD_DIR + "monster"
#define EARTHSEA_OBJECT      EARTHSEA_STD_DIR + "object"
#define EARTHSEA_CONTAINER   EARTHSEA_STD_DIR + "container"
#define EARTHSEA_CREATURE    EARTHSEA_STD_DIR + "creature"

#define GONT_DIR             EARTHSEA_DIR + "gont/"
#define ORANEA_DIR           EARTHSEA_DIR + "oranea/"
#endif
