/* /d/Earthsea/sys/properties.h - header file for domainwide properties
 * 
 * DO NOT EDIT THIS FILE unless you have explicitly been given
 * permission to do so.  If you have been given permission, and
 * you edit this file, BE SURE THAT THERE ARE NO ERRORS in it.
 *
 * This is not a place for every property used in the domain.
 * Only add a property here if it is truly to be used throughout
 * the domain.
 */

#ifndef EARTHSEA_PROPERTIES
#define EARTHSEA_PROPERTIES

#define ROOM_I_TERRAIN_TYPE "_room_i_terrain_type"

#endif
