/* /d/Earthsea/sys/skills.h - header file for domain skill definitions
 *
 * DO NOT EDIT THIS FILE unless you have explicitly been given
 * permission to do so.  If you have been given permission, and
 * you edit this file, BE SURE THAT THERE ARE NO ERRORS in it.
 *
 * ALL DOMAIN SKILLS SHOULD BE IN THIS FILE.  It is important
 * that all domain skills are here so that there is no chance
 * of reusing a skill number.
 *
 * NOTE: Earthsea domain skills should be in the range 147000 - 147999
 */

#ifndef EARTHSEA_SKILLS
#define EARTHSEA_SKILLS

#endif
