   set_act_time(10);
   add_act("emote stares at you suspiciously.");
   add_act("emote eyes his weapon anxiously.");
   add_act("say Your every order shall be followed strictly, your grace.");
   add_act("say We shall send a messenger to the special forces, as ordered.");
   add_act("say I am confident we will drive the foreigners out, your grace.");
   add_act("emote salutes obediently.");
   add_act("say The followers of false gods shall not spread their foul teachings here.");
   add_act("say The streets of Argos shall flow with the blood of loyalists.");
   set_cact_time(3);
   add_cact("emote swings his weapon over his head triumphantly.");
   add_cact("shout You shall die for your intrusion, infidel!");
   add_cact("shout I shall crush your head like a melon, infidel!");
   add_cact("emote cackles maniacally with an evil glare.");
   add_cact("say Your corpse on a pole shall be a warning to others, intruder!");
   add_cact("say Your kind will be crushed by the heel of Kretos, infidel!");
   add_cact("emote yells a shrill battle cry!");
