   set_act_time(10);
   add_act("emote stares at you suspiciously.");
   add_act("shout Be ready to attack men! They won't pass here!");
   add_act("shout Be vigilant men! There are intruders in the area.");
   add_act("shout Wash the road with their blood, men!");
   add_act("emote looks out over the road.");
   add_act("emote paces impatiently.");
   set_cact_time(5);
   add_cact("emote swings his weapon over his head triumphantly.");
   add_cact("shout You shall die for your intrusion, infidel!");
   add_cact("shout I shall crush your head like a melon, infidel!");
   add_cact("emote cackles maniacally with an evil glare.");
   add_cact("say Your corpse on a pole shall be a warning to others, intruder!");
   add_cact("say Your kind will be crushed by the heel of Kretos, infidel!");
   add_cact("emote yells a shrill battle cry!");
