kender ({"Secret Society of Uncle Trapspringer",1,0,0,})
calians ({"Calian warrior's guild",1,0,0,})
glads ({"Gladiator guild",1,0,0,})
union ({"Union of the Warriors of Shadow",1,0,0,})
rangers ({"Gondorian Rangers Guild",1,0,0,})
worshipper ({"Elemental Worshippers of Calia",0,1,0,})
neidar ({"Dwarven Warriors of the Neidar Clan",1,0,0,})
monks ({"Ancient Kaheda Order",1,1,0,})
smiths ({"The Smiths Guild",0,1,0,})
knights ({"Solamnian Knights",1,0,0,})
cadets ({"Cadets of Gelan",0,1,0,})
minstrels ({"The August Order of Minstrels",0,1,0,})
trickster ({"Tricksters",0,1,0,})
blademasters ({"Blademasters of Khalakhor",0,1,0,})
heralds ({"Heralds of the Valar",0,1,0,})
hobbits ({"Adventuresome Hobbits Guild",0,0,1,})
vampires ({"Vampires of Emerald",1,0,0,})
