
#include "../defs.h"
#define AULAKI "/d/Calia/walkers/fire/spells/aulaki.h"
#define PURKAGIA "/d/Calia/walkers/fire/spells/purkagia.h"
#define ASTRAPHTO "/d/Calia/walkers/fire/spells/astraphto.h"
#define AERAS "/d/Calia/walkers/fire/spells/aeras.h"
#define SAITA "/d/Calia/walkers/fire/spells/saita.h"
#define ASPIDA "/d/Calia/walkers/fire/spells/aspida.h"
#define THERAPEAOU "/d/Calia/walkers/fire/spells/therapeaou.h"
#define GSECHON "/d/Calia/walkers/fire/spells/gsechon.h"
#define PYRONERO "/d/Calia/walkers/fire/spells/pyronero.h"
#define PHOTITSO "/d/Calia/walkers/fire/spells/photitso.h"
#define TUPHLONO "/d/Calia/walkers/fire/spells/tuphlono.h"
#define OPTASIA "/d/Calia/walkers/fire/spells/optasia.h"
#define PHOTOSTEPSANOS "/d/Calia/walkers/fire/spells/photostepsanos.h"
#define AEMERA "/d/Calia/walkers/fire/spells/aemera.h"
#define HAGIOSPYRO "/d/Calia/walkers/fire/spells/hagiospyro.h"
#define BRADU "/d/Calia/walkers/fire/spells/bradu.h"
#define AKOUTARI "/d/Calia/walkers/fire/spells/akoutari.h"
#define ANTHISTO "/d/Calia/walkers/fire/spells/anthisto.h"
#define PHLOGAPHULO "/d/Calia/walkers/fire/spells/phlogaphulo.h"
#define STOIECHEIO "/d/Calia/walkers/fire/spells/stoiecheio.h"
#define KAUSAE "/d/Calia/walkers/fire/spells/kausae.h"

#define IS_FIRE(ob) (ob->query_guild_name_occ() == GUILD_NAME)
#define GUILD_MEMBERS "/d/Calia/walkers/texts/guild_members"
