// file name:        /d/Avenir/common/holm/shore/sh26.c
// creator(s):       Lilith, April 97
// revisions:
// purpose:
// note:
// bug(s):
// to-do:

/* Inherit the room that is the base for the area. */
inherit "/d/Avenir/common/holm/shore/shore_base";

/* Include the local area defines, etc */
#include "/d/Avenir/common/holm/holm.h"

/*
 * Function name: reset_domain_room
 * Description:   This function should be used for for reseting herbs
 */
void reset_domain_room()
{
    set_searched(0);
    ::reset_domain_room();
}



/* Now create the room.  */
void
create_shore_room()
{
    set_short("Wide ledge of rock, covered with sand");
    set_long("This is a wide stone ledge beyond the reach of the sea. "+
        "It is covered in a fine, cushioning layer of black sand. "+
        "From here there is an excellent view of the Sybarus Sea and "+
        "the southern portions of the Holm. You can also see the "+
        "Spire rising inland, a great wave of dark stone standing "+
        "sentinel over the island. The air is laden with a "+
        "fine mist generated by the thrashing of the tide against "+ 
        "the stones below."+
        "\n");
    add_item(({"spire", "Spire", "inland", "east"}),
        "The Spire rises east of here, towering above the jungle. "+
        "From this angle it looks like a dark wave topped with pale "+
        "green foam, caught eternally in that moment just prior "+
        "to breaking, carved in ageless stone.\n");
    add_item(({"Holm", "holm", "south", "haze"}),
        "You can see this, the western shore of the Holm, pummeled "+
        "by waves and wind. It goes on as far as your eyes can see, "+
        "concealed by a pale haze.\n");
    add_beachs();
    add_rocks();
    add_exit("sh24", "northwest", 0);
    add_exit("sh25", "down", 0);
    reset_domain_room();
}

