/*
 * AREA_HANDLER AUTOGENERATED ROOM
 *
 * DO NOT CHANGE ANYTHING IN THIS ROOM SINCE THE ROOM
 * AUTOREMOVES ITSELF REGULARLY.
 */

inherit "/d/Earthsea/std/room";
#include "/d/Earthsea/sys/room_defs.h"
#include <stdproperties.h>
#include <macros.h>
#define TO this_object()

string	Master_ob;	/* The master object */
int	Timeout;	/* Timeout time */

public nomask void set_cleanup_time(int time);

create_earthsea_room()
{
    setuid();
    seteuid(getuid());

    BAY
