#define CALIAN "Calian warrior's guild"
#define DRAGONARMY "Dragonarmy"
#define GLADIATOR "Gladiator guild"
#define MORGUL "Morgul Mages"
#define RANGER "Gondorian Rangers Guild"
#define MONK "Order of the Dragon"
#define KNIGHT "Solamnian Knights"
#define ANGMAR "Angmar Army"
#define SHADOW_UNION "Union of the Warriors of Shadow"
#define NEIDAR "Dwarven Warriors of the Neidar Clan"
