inherit "/std/room";
#include "/sys/macros.h"
#include "/sys/stdproperties.h"
#include "defs.h"
 
 
string my_long();
void
create_room()
 {
  set_short("Rocky Barrens");
    set_long(my_long()+"\n");
    add_exit(SOUTH + "d8","west");
    add_exit(SOUTH + "d10","east");
    add_exit(SOUTH + "d12","northeast");
    add_exit(SOUTH + "d13","north");
    add_exit(SOUTH + "d14","northwest");
    add_exit(SOUTH + "d1","south");
    add_exit(SOUTH + "d2","southwest");
add_item(({"rocks","rock"}),"They lie scattered about randomly, sharp, "
        +"wind eroded edges biting at your feet.\n");
add_item("dust","The ever present dust of "
        +"Athas is everywhere.  When it is not being kicked up "
    +"by your footsteps, it is blowing around on the dry "
        +"winds that swirl constantly.\n");
add_item("sand","Sand is everywhere here, from the salt flats "
        +"to towering sand dunes.  It is almost as prevalent as "
        +"as the dust that seems to end up in or on everything.  "
        +"Sometimes the sand is coarse and rough, sometimes it is "
        +"so fine it is like silk.  Whatever form its in, its "
        +"always here.\n");
add_item(({"salt","crystals","salt crystals","crystal"}),
        "The remnants of some long forgotten body of water, these "
        +"salt crystals now form are mingled with regular sand "
        +"in many of the salt flats that are present in Athas.  "
        +"The salt reflects the sun more brightly than regular "
        +"sand does, hence the glare her is very bad.\n");
add_item(({"mountains","ringing mountains"}),"Standing tall and "
        +"imperious to your north, the Ringing Mountains stand "
        +"as the northern guardians of Tyr.  Iron is mined from "
        +"them by the order of Kalak, sorcerer king of Tyr.  "
        +"There are also tales of roving monster hordes that hide "
        +"in the mountains, using ancient fortresses and caverns.\n");
add_item(({"dune","dunes"}),"Sand dunes ripple through the desert "
        +"outward from Tyr, as if Tyr were a stone dropped in a "
        +"pond.  Sometimes high, sometimes low, the dunes are "
        +"fairly constant in appearance, and only vary in size "
        +"and shape.\n");
 
 
}
 
string
my_long()
{
string *long;
long = ({"Dry, hard packed ground seems to stretch out towards the "
        +"horizon as you walk across the barrens.  Small rocks litter "
        +"the ground here, obviously chunks from larger boulders that "
        +"have been worn by the scouring winds that swirl through here.  "
        +"There is no plant life here at all, nor even the hint of any.",
        "You are in the midst of an area covered with small broken "
        +"pieces of rocks and earth.  In this dry unforgiving waste you "
        +"see no signs of plant life at all, not even the tough desert "
        +"plants can survive here.  The heat of the sun pounds into "
        +"you remorselessly, a constant reminder of what is in charge "
        +"here","Dust kicked up by the wind blows into your face, drying "
        +"your mouth and stinging your eyes as you cross the rocky "
        +"barrens here.  Cracks stretch like mazes over the rock-hard "
        +"dried soil, linking together like some vast river.  High "
        +"overhead, a lone creature sails aloft on the powerful winds "
        +"generated by the intense heat radiating up from the ground.  "
        +"Even though you can barely see it, you can feel its cold "
        +"eyes on you.","The whistling of wind and the slapping of your "
        +"shoes on the hard earth is all that you hear as you walk "
        +"across the scorched, rocky earth here.  Small chunks of "
        +"rock lay scattered across the ground like the shattered "
        +"skeletal remnants of some ancient beast."});
 
   return long[random(sizeof(long))];
}


