
#include "../defs.h"
#define NERO_POTION_OBJECT "/d/Calia/walkers/potions/nero_ob"
#define NERO_TIME 600
#define AULAKI_POTION_OBJECT "/d/Calia/walkers/potions/aulaki_ob"
#define AULAKI_TIME 300
#define BRADU_POTION_OBJECT "/d/Calia/walkers/potions/bradu_ob"
#define BRADU_TIME 300
#define AERTROPHIA_POTION_OBJECT "/d/Calia/walkers/potions/aertrophia_ob"
#define AERTROPHIA_TIME 300
#define AKOUTARI_POTION_OBJECT "/d/Calia/walkers/potions/akoutari_ob"
#define AKOUTARI_TIME 150
#define PICHNO_POTION_OBJECT "/d/Calia/walkers/potions/pichno_ob"
#define PICHNO_TIME 150
#define ASPIDA_POTION_OBJECT "/d/Calia/walkers/potions/aspida_ob"
#define ASPIDA_TIME 360
#define OCHETOS_POTION_OBJECT "/d/Calia/walkers/potions/ochetos_ob"
#define OCHETOS_TIME 360
#define SAITA_POTION_OBJECT "/d/Calia/walkers/potions/saita_ob"
#define SAITA_TIME 120
#define TOPI_POTION_OBJECT "/d/Calia/walkers/potions/topi_ob"
#define TOPI_TIME 120
#define UPALA_POTION_OBJECT "/d/Calia/walkers/potions/upala_ob"
#define UPALA_TIME 120
#define PURKAGIA_POTION_OBJECT "/d/Calia/walkers/potions/purkagia_ob"
#define PURKAGIA_TIME 120
#define OPTASIA_POTION_OBJECT "/d/Calia/walkers/potions/optasia_ob"
#define OPTASIA_TIME 600
#define AERAS_POTION_OBJECT "/d/Calia/walkers/potions/aeras_ob"
#define AERAS_TIME 120
#define PLEKO_POTION_OBJECT "/d/Calia/walkers/potions/pleko_ob"
#define PLEKO_TIME 120
#define PHOTOSTEPSANOS_POTION_OBJECT "/d/Calia/walkers/potions/photostepsanos_ob"
#define PHOTOSTEPSANOS_TIME 60
#define ANTHISTO_POTION_OBJECT "/d/Calia/walkers/potions/anthisto_ob"
#define ANTHISTO_TIME 60
#define ANTIDROAERA_POTION_OBJECT "/d/Calia/walkers/potions/antidroaera_ob"
#define ANTIDROAERA_TIME 60
#define STOIECHEIO_POTION_OBJECT "/d/Calia/walkers/potions/stoiecheio_ob"
#define STOIECHEIO_TIME 60
#define DIARROAE_POTION_OBJECT "/d/Calia/walkers/potions/diarroae_ob"
#define DIARROAE_TIME 60
#define HAGIOSPYRO_POTION_OBJECT "/d/Calia/walkers/potions/hagiospyro_ob"
#define HAGIOSPYRO_TIME 60
#define PHLOGAPHULO_POTION_OBJECT "/d/Calia/walkers/potions/phlogaphulo_ob"
#define PHLOGAPHULO_TIME 60
#define KAUSAE_POTION_OBJECT "/d/Calia/walkers/potions/kausae_ob"
#define KAUSAE_TIME 60
#define LEPIDA_POTION_OBJECT "/d/Calia/walkers/potions/lepida_ob"
#define LEPIDA_TIME 60
#define EPIKANOMAI_POTION_OBJECT "/d/Calia/walkers/potions/epikanomai_ob"
#define EPIKANOMAI_TIME 60

