/* Hallowed cavern (from the orcish point of view).

   Code (c) 2000 to Damian Horton - BKA Casimir.
*/
 
#pragma strict_types
#pragma save_binary 

#include <stdproperties.h>
#include <macros.h>
#include <ss_types.h>
#include "/d/Emerald/sys/paths.h"

inherit BLACKWALL_DIR + "orcs/base_cave";

void
create_cave()
{   
    set_river_room(); // the river flows through this room

    set_short("West side of a large cavern");
    set_em_long("West side of a large cavern. A river flows along the "+
	     "eastern wall of the cavern. Piles of dung generated by some "+
	     "creature lay strewn about the cavern floor. The "+
	     "western wall of the cavern takes a turn to the southeast "+
	     "here.\n");

    add_item(({"feces", "piles", "piles of feces", "dung", "piles of dung"}),
	     "Frequent piles of feces make walking through this portion "+
	     "of the cavern treacherous and do nothing to improve the "+
	     "stagnant quality of the air. Their general shape is consistent "+
	     "with that produced by many humanoid species.\n");

     add_item(({"ground", "floor", "cavern floor", "down"}),
	      "The cavern floor has been carved out of black rock via many "+
	      "years of water action. It is rough and uneven, with "+
	      "pools of moisture forming at the low points. The cavern "+
	      "floor is littered with piles of dung.\n");
    
    add_exit(BLACKWALL_DIR + "orcs/cave4", "north");
    add_exit(BLACKWALL_DIR + "orcs/cave5", "northeast");
    add_exit(BLACKWALL_DIR + "orcs/cave9", "east");
    add_exit(BLACKWALL_DIR + "orcs/cave12", "southeast");
}

/* Modified from the original to account for the orc droppings. */
public void
hook_smelled(string arg)
{    
    if (river_room && ((arg == "river") || (arg == "stream") || 
		       (arg == "water")))
    {
	write("The river doesn't smell particularly good, though perhaps "+
	      "it is because you cannot get the overall scent of the "+
	      "cavern out of your nose.\n");
	return;
    }
  
    if ((arg == "feces") || (arg ==  "dung") || (arg == "piles of feces") ||
	(arg == "piles of dung"))
    {
	write("EWWWW! How do you expect it smells?!\n");
	say(QCTNAME(this_player()) + " kneels down and takes a deep breath "+
		    "near one of the piles of dung!\n");
	return;
    }
    
    else if (strlen(arg))
    {
	// player attempted to smell something in the room other than
	// water
	return;
    }

    // player smelt the room in general:

    write("This portion of the cavern smells heavily of the piles of feces "+
	  "under your foot.\n");
}


void
init()
{
    ::init();
    add_action(drink_from_river, "drink");
}
                 






